### ISSUE TITLE
Remove line number from ERROR_COUNTER metric

### ISSUE THREAD

**Issue by jeffbakerexpedia** [ExpediaDotCom/haystack-pipes#265]
Scaling issues with InfluxDb have led us to change the way that Graphite messages are changed into tagged metrics in InfluxDb; in particular, the InfluxDb template for the error metrics was changed from "haystack.errors.* system.metricGroup.subsystem.fqClass.host.lineNumber.measurement*" to "haystack.errors.* measurement.measurement.measurement.fqClass.host.field*". As a result, the presence of line number in the metric needs to be removed. Changes to the custom appenders packages have been made; the new versions of those packages are needed in haystack-pipes.

**Comment by shreyaa-sharma** [comment]
Done and closing this.
